################# English language (default) ################
[en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 1

# Multi-language support disabled - only English is active
# To re-enable other languages, uncomment the sections below

# ################ French language ##################
# [fr]
# languageName = "Fran√ßais"
# languageCode = "fr-FR"
# contentDir = "content/french"
# weight = 2

# ################ Italian language #################
# [it]
# languageName = "Italiano"
# languageCode = "it-IT"
# contentDir = "content/italian"
# weight = 3

# ################ German language ##################
# [de]
# languageName = "German"
# languageCode = "de-at"
# contentDir = "content/german"
# weight = 4